# Generated by Django 2.2.7 on 2019-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
